[build]
  command = "cp env.example.js env.js && sed -i \"s|process.env.WEATHER_API_KEY|'$WEATHER_API_KEY'|\" env.js && sed -i \"s|process.env.SECOND_API_KEY|'$SECOND_API_KEY'|\" env.js && sed -i \"s|process.env.TOMORROW_API_KEY|'$TOMORROW_API_KEY'|\" env.js"
  publish = "."